# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sponsor',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(default='', max_length=128),
        ),
    ]
