# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
