# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181221_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='grade_list',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userfile',
            name='jury_list',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='juryfile',
            name='file_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='juryfile',
            name='finished_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='jury_count',
            field=models.IntegerField(default=0),
        ),
    ]
