# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181224_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Comp', 'Competitor'), ('Org', 'Organizer'), ('Rat', 'Jury'), ('SU', 'SuperUser')], default='Comp', max_length=20),
        ),
    ]
