# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181220_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='uniq_id',
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='competition_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jury',
            name='competition_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='competition_list',
            field=models.TextField(default=''),
        ),
    ]
