# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181225_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='school',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='juryfile',
            name='competition',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='juryfile',
            name='file_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='juryfile',
            name='jury',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='competition',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_url',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
