# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181225_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='age',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='competitor',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competitor',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jury',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jury',
            name='school',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organizer',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='school',
            field=models.CharField(default='', max_length=128),
        ),
    ]
