# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-04 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190104_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.TextField(default=''),
        ),
    ]
