# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-04 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190104_1307'),
        ('website', '0005_auto_20181227_1202'),
    ]

    operations = [
    ]
