# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-04 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_merge'),
        ('website', '0005_auto_20181227_1237'),
    ]

    operations = [
    ]
